version: '3.7'

services:
  web:
    image: chouhanaryan/imw_web:latest
    build:
      context: ./web
    command: gunicorn inventory_management.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
  
  nginx:
    image: chouhanaryan/imw_nginx:latest
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  static_volume: